export { default as Home } from "./Home"
export { default as Menu } from "./Menu"
export { default as Locations } from "./Locations"
export { default as Us } from "./Us"
export { default as NotFound } from "./NotFound"
